export const hrChatRooms = [
  {
    id: "student-tanaka",
    role: "student",
    roleLabel: "学生",
    name: "田中 太郎",
    detail: "青山大学・二次面接",
    status: "日程調整中",
    lastMessage: "ありがとうございます！確認いたします。",
    reply: ["ありがとうございます！", "確認いたします。"],
    time: "10:32",
    unread: 2,
  },
  {
    id: "student-sato",
    role: "student",
    roleLabel: "学生",
    name: "佐藤 花子",
    detail: "明和大学・一次面接",
    status: "候補日回答待ち",
    lastMessage: "日程調整のご案内を送信しました。",
    reply: ["日程を確認しました。", "本日中に回答いたします。"],
    time: "昨日",
    unread: 0,
  },
  {
    id: "student-yamamoto",
    role: "student",
    roleLabel: "学生",
    name: "山本 健",
    detail: "東都大学・最終面接",
    status: "面接確定",
    lastMessage: "当日はよろしくお願いいたします。",
    reply: ["ご連絡ありがとうございます。", "当日はよろしくお願いいたします。"],
    time: "8/30",
    unread: 0,
  },
  {
    id: "interviewer-suzuki",
    role: "interviewer",
    roleLabel: "面接官",
    name: "鈴木 一郎",
    detail: "開発部・エンジニア面接担当",
    status: "対応可能",
    lastMessage: "9月8日の面接、承知しました。",
    reply: ["日程を確認しました。", "9月8日で問題ありません。"],
    time: "11:05",
    unread: 1,
  },
  {
    id: "interviewer-takahashi",
    role: "interviewer",
    roleLabel: "面接官",
    name: "高橋 美咲",
    detail: "事業企画部・最終面接担当",
    status: "予定登録済み",
    lastMessage: "来週の空き予定を登録しました。",
    reply: ["来週の空き予定を登録しました。", "ご確認をお願いします。"],
    time: "9:48",
    unread: 0,
  },
  {
    id: "interviewer-ito",
    role: "interviewer",
    roleLabel: "面接官",
    name: "伊藤 誠",
    detail: "営業部・一次面接担当",
    status: "確認待ち",
    lastMessage: "候補日時を確認しています。",
    reply: ["候補日時を確認しています。", "少々お待ちください。"],
    time: "8/29",
    unread: 0,
  },
  {
    roleLabel: "他人事",
    status: "オンライン",
    lastMessage: "田中さんの面接官調整を進めます。",
    reply: ["共有ありがとうございます。", "こちらで面接官調整を進めます。"],
    time: "10:15",
    unread: 3,
  },
  {
    id: "hr-nakamura",
    role: "hr",
    roleLabel: "人事",
    name: "中村 翔太",
    detail: "人事部・中途採用担当",
    status: "離席中",
    lastMessage: "候補者情報を更新しました。",
    reply: ["候補者情報を更新しました。", "内容をご確認ください。"],
    time: "8/28",
    unread: 0,
  },
]

export const findHrChatRoom = (id) => hrChatRooms.find((room) => room.id === id)
